# Site settings
title: Mayhem
description: > # this means to ignore newlines until "baseurl:"
    Mayhem. The cool kid on the block.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mayhem.mmay.rocks" # the base hostname & protocol for your site
twitter_username: ohaimmay
github_username:  mmay

# Build settings
markdown: kramdown
