# Site settings
title: Mayhem
description: > # this means to ignore newlines until "baseurl:"
    Mayhem.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://m.mmay.rocks" # the base hostname & protocol for your site
twitter_username: ohaimmay
github_username:  mmay

# Build settings
markdown: kramdown
